version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
    environment:
      - VIRTUAL_HOST=jaeger-ui.localhost
      - VIRTUAL_PORT=16686

  php:
    image: fluxoti/php:7.2-web
    volumes:
      - ./:/var/www/app
    depends_on:
      - nginx-proxy
      - jaeger
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=*.jaeger-demo.localhost,jaeger-demo.localhost
      - VIRTUAL_PORT=8080
